# Generated by Django 2.0.6 on 2018-06-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('risk', models.IntegerField(choices=[(0, 'None Selected'), (1, 'Conservative'), (2, 'Balanced'), (3, 'Growth'), (4, 'Aggresive')], default=0)),
            ],
        ),
    ]
